---
title: "Transform"
author: "Vyoma Sheth"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Loading packages for transforming the categorical Fin Tech data into usable format
1. Import the data 
```{r}
Data <- read.csv("Data.csv", header=TRUE)
```
 2. Normalize age and amount between particular values
```{r}
Data$Age <- normalize(Data$Age, method = "standardize", range = c(18, 100))
Data$Amount <- normalize(Data$Amount, method = "standardize", range = c(0, 500))
```
3. Replace values of gender to 0 and 1
```{r}
Data$gender <- factor(Data$gender, levels = c("m", "f"), labels = c(0,1))
```
4. Apply one hot encoding function for better visulization of data
```{r}
Data <- one_hot(as.data.table(Data), naCols = TRUE)
Data <- as.data.frame(Data)
Data$v1 <- normalize(Data$v1, method = "standardize", range = c(-5, 5))
Data$v2 <- normalize(Data$v2, method = "standardize", range = c(-5, 5))
Data$v3 <- normalize(Data$v3, method = "standardize", range = c(-5, 5))
Data$v4 <- normalize(Data$v4, method = "standardize", range = c(-5, 5))
``` 
5. Normalize the data accoring to the card type used
```{r}
Data["v3*v4*Visa"] = Data$v3*Data$v4*Data$cardType_Visa
Data["v1*v2*Master"] = Data$v1*Data$v2*Data$cardType_Master
```
